const MODES = {
  '0': 'No Transport',
  '1': 'Road',
  '2': 'Air',
  '3': 'Ocean',
  '4': 'Rail',
  '7': 'Courier',
  '0': 'Multi-Modal',
};
const DIRECTIONS = {
  '0': 'N/A',
  '1': 'Export',
  '2': 'Import',
  '3': 'Domestic',
};
const BOOKING_STATUSES = {
  '000': 'Incomplete/Invalid',
  '015': 'EDI Redirected',
  '025': 'EDI Received Job',
  '050': 'Received via J2J',
  '200': 'Unconfirmed Job',
  '250': 'Unconfirmed Job Linked to Master',
  '800': 'Confirmed',
  '900': 'Closed',
  '950': 'Job Canceled',
};
const SERVICE_TYPES = {
  '0': 'Breakbulk',
  '1': 'Direct',
  '2': 'Consol',
  '3': 'Full Load',
  '4': 'Warehousing',
  '5': 'Brokerage',
  '6': 'Ancillary Support Services',
  '7': 'Fairs',
};
const SERVICE_LEVELS = {
  AS: 'Administrational Support',
  A1: 'Air Expedited',
  A2: 'Air Premier',
  A3: 'Air Value',
  BC: 'BUSINESS CRITICAL (DTS)',
  BD: 'Brokerage + Distribution',
  BE: 'Bonded Warehousing Entries',
  BK: 'Breakbulk / Non-Containerized',
  BO: 'Bonded Warehousing Only',
  BR: 'Brokerage Only',
  BS: 'SIN-BTM Barge Service',
  BW: 'Bonded Warehousing + Distribution',
  CC: 'Customs Consultancy',
  CH: 'Charter',
  CO: 'Courier',
  CY: 'Logistics Consultancy',
  DN: 'Delivery Note Job (Customer Consol)',
  DR: 'Direct',
  D1: 'DHL Europe',
  D2: 'DHL Documents',
  D3: 'DHL Dutiable',
  EX: 'Express',
  FM: 'Freight Management',
  FR: 'Fairs',
  F1: 'Sea Premier FCL',
  GD: 'Ground',
  IN: 'Insurance',
  L1: 'Sea Premier LCL',
  L2: 'LCL CFS/CY',
  MS: 'Marine Services',
  NA: 'Overnight (For DTS use only)',
  PS: 'Procurement Services',
  PT: 'Priority',
  RO: 'Roll On / Roll Off',
  SA: 'Sea/Air',
  SD: 'Statistical Data Collation',
  SP: 'Speedpac',
  ST: 'Standard',
  TB: 'Third Party Billing',
  TL: 'Trucker LTL',
  TN: 'TransNatur (Switzerland Only)',
  T1: 'TNT Next Days',
  T2: 'TNT 2-3 Days',
  T3: 'TNT 4 Days',
  UD: 'Unbonded Warehousing + Distribution',
  UW: 'Unbonded Warehousing Only',
  U1: 'UPS Europe',
  U2: 'UPS Documents',
  U2: 'UPS Dutiable',
  WA: 'G14A - GEO 14 Day DTA',
  WB: 'G2A - 2-day DTA Intra Asia-PPD/Add',
  WC: 'GPC2/4-GEO 4 day INT XDOCK',
  WD: 'G8D - GEO 8 DAY DTD',
  WE: 'GE1 - Intra Europe Overnight',
  WF: 'G2D - 2-day DTD Intra Asia-PPD/Add',
  WG: 'W4a - 4-day DTA PPD/Add Freight',
  WH: 'W4D - 4-day DTD PPD/Add Freight',
  WI: 'GA2 - GeoLogistics Intra Asia 2-day',
  WJ: 'GE4 - Intra Europe 4 days',
  WK: 'GO5 - International Emerging Mkt',
  WL: 'G4D - 4-day TDT Prepaid',
  WM: 'GO3A - OEM Intl DTD 3 day',
  WN: 'GN1 - Intra N America Overnight',
  WO: 'GO1 - DTD 1 day',
  WP: 'GO4A - OEM Intl DTD 4 day',
  WQ: 'GO3B - OEM Intl DTD 4 day',
  WR: 'GA4 - GEO INTRA ASIA 4 DAY',
  WS: 'GO3C - OEM Intl DTD 5 day',
  WT: 'GT3 - Full Truckload 2/3 days',
  WU: 'GL1 - GeoLogistics Local 1 Day Srvc',
  WV: 'GO4C - OEM Intl DTD 6 day',
  WW: 'GPM3-GEO INTL 3 DAY DTD',
  WX: 'GPM4-GEO INTL 4 DAY DTD',
  WY: 'GPC2/2-GEO 2DAY INT XDOCK',
  WZ: 'GPC2/3-GEO 3DAY INT XDOCK',
  W1: 'GT1 - Full Truckload Overnight',
  W2: 'GO2 - International DTD 2 day',
  W3: 'GO3 - International DTD 3 day',
  W4: 'GO4 - International DTD 4 day',
  W5: 'GE2 - Intra Europe 2 day',
  W6: 'GE3 - Intra Europe 3 days',
  W7: 'G7A - GEO 7 DAY DTA',
  W8: 'GN3 - Intra N America 3 days',
  W9: 'GPM2-GEO INTL 2 DAY DTD',
  '2D': 'Second Day Service (DTS use only)',
  '3D': '3rd Day Service (DTS Use Only)',
};
const COUNTRY_CODES = [
  'AE',
  'AR',
  'AT',
  'AU',
  'BA',
  'BD',
  'BE',
  'BG',
  'BH',
  'BR',
  'CA',
  'CH',
  'CL',
  'CN',
  'CO',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'EG',
  'ES',
  'FI',
  'FR',
  'GB',
  'GH',
  'GR',
  'GT',
  'HK',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IN',
  'IQ',
  'IS',
  'IT',
  'JO',
  'JP',
  'KE',
  'KH',
  'KR',
  'KW',
  'KZ',
  'LB',
  'LK',
  'LT',
  'LU',
  'LV',
  'MA',
  'MG',
  'MT',
  'MU',
  'MX',
  'MY',
  'NA',
  'NL',
  'NO',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PG',
  'PH',
  'PK',
  'PL',
  'PR',
  'PT',
  'QA',
  'RO',
  'RS',
  'RU',
  'SA',
  'SE',
  'SG',
  'SI',
  'SK',
  'TH',
  'TN',
  'TR',
  'TW',
  'UA',
  'US',
  'VN',
  'ZA',
];
